# Generated by Django 5.2 on 2025-04-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_skills_organization_city_organization_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="location",
            new_name="address",
        ),
    ]
