# Generated by Django 5.2 on 2025-04-18 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_location_userprofile_address"),
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobposts",
                to="account.citiesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("Work from home", "Work from home"),
                    ("Hybrid", "Hybrid"),
                    ("Onsite", "Onsite"),
                ],
                max_length=200,
            ),
        ),
    ]
