# Generated by Django 5.2 on 2025-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_jobpost_location_alter_jobpost_location_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="job_name",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="experience_required",
            field=models.CharField(
                choices=[
                    ("Fresher", "Fresher"),
                    ("0-1 Year", "0-1 Year"),
                    ("1-2 Year", "1-2 Year"),
                    ("2-3 Year", "2-3 Year"),
                    ("3-4 Year", "3-4 Year"),
                    ("4-5 Year", "4-5 Year"),
                    ("5+ Year", "5+ Year"),
                ],
                default="none",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
