# Generated by Django 5.2 on 2025-04-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_location_userprofile_address"),
        ("myapp", "0003_remove_jobpost_job_name_jobpost_experience_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobposts",
                to="account.citiesmodel",
            ),
        ),
    ]
