# Generated by Django 5.2 on 2025-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_jobpost_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="employment_type",
            field=models.CharField(
                choices=[("full_time", "Full-time"), ("part_time", "Part-time")],
                default="full_time",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="job_type",
            field=models.CharField(
                choices=[("internship", "Internship"), ("job", "Job")],
                default="job",
                max_length=10,
            ),
        ),
    ]
