# Generated by Django 5.0.7 on 2026-04-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_jobpost_applied_users_jobpost_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
